import primality_test
import commonMultiples
import random
import secrets

#To generate an RSA key you need large prime numbers. For code checking purposes the primes are kept smaller here.
#RSA keys are generated by taking two primes and multiplying each prime-1 together.
#And then finding a random exponenent that is relatively prime to the composite number.
#This exponent will be used for encryption of messages.


class keyGenerator:    
    def __generate_primes(self):
        is_p_prime = False
        while not is_p_prime:
            p = int.from_bytes(secrets.token_bytes(6),"little")
            is_p_prime = primality_test.testPrime(p)

        is_q_prime = False
        while not is_q_prime: 
            q = int.from_bytes(secrets.token_bytes(6),"little")
            is_q_prime = primality_test.testPrime(q)
        return p,q

    def __generate_e(self,p,q):
        composite = (p-1)*(q-1)
    
        e_found = False
        while not e_found:
            e = random.randrange(1,composite)
            if(commonMultiples.gcd(composite, e) == 1):
                e_found = True
    
        return e
    
    def getKeys(self):
        p,q = self.__generate_primes()
        
        e = 65537 #Boneh, Dan (1999). "Twenty Years of attacks on the RSA Cryptosystem". Notices of the American Mathematical Society. 46 (2): 203–213.
        N = p*q
        composite = (p-1)*(q-1)
        
        print(composite)

        return e,N,composite


