import primality_test
import greatest_common_divisor
import random

#To generate an RSA key you need large prime numbers. For code checking purposes the primes are kept smaller here.
#RSA keys are generated by taking two primes and multiplying each prime-1 together.
#And then finding a random exponenent that is relatively prime to the composite number.
#This exponent will be used for encryption of messages.


class keyGenerator:    
    def __generate_primes(self):
        is_p_prime = False
        while not is_p_prime:
            p = random.randrange(100,200)
            is_p_prime = primality_test.testPrime(p)

        is_q_prime = False
        while not is_q_prime: 
            q = random.randrange(100,200)
            is_q_prime = primality_test.testPrime(q)
        return p,q

    def __generate_e(self,p,q):
        composite = (p-1)*(q-1)
    
        e_found = False
        while not e_found:
            e = random.randrange(1,composite)
            if(greatest_common_divisor.gcd(composite, e) == 1):
                e_found = True
    
        return e
    
    def getKeys(self):
        p,q = self.__generate_primes()
        
        e = self.__generate_e(p,q)
        N = p*q
        composite = (p-1)*(q-1)
                
        return e,N,composite
